### ISSUE TITLE
Updating to snapshot 160 breaks Python support

### ISSUE THREAD

**Issue by romainl** [macvim-dev/macvim#979] opened 2019-10-29 22:29 UTC
**Describe the bug**
The Python interface no longer works after updating MacVim from snapshot 159 to snapshot 160.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Put the lines below in `/tmp/pythontest.vim` to tell Vim where to find Python 3.7:

        " this is from MacPorts, use a path that works for you
        let &pythonthreehome = '/opt/local/Library/Frameworks/Python.framework/Versions/3.7'
        let &pythonthreedll = '/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib'

3. Start the TUI with:

        $ mvim -vNu /tmp/pythontest.vim

   or the GUI with:

        $ mvim -gNu /tmp/pythontest.vim

4. Do `:echo has('python3')`.

5. Get a `0`.

6. Do `:py3 print(1)`.

7. Get the following errors:

        E370: Could not load library /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib
        E263: Sorry, this command is disabled, the Python library could not be loaded.

**Expected behavior**
Both commands should echo `1`, without throwing errors.

**Environment:**
 - Vim version: 8.1.2224 (160)
 - OS: macOS 10.14.6
 - Terminal: Terminal.app and the GUI

**First reported:**
https://www.reddit.com/r/vim/comments/dotqki/macvim_black_and_python_version_problem/

**Comment by eirnym** [comment] 2019-10-30 05:45
@romainl Thank you for an issue,

It's a known problem, #978

**Comment by RStankov** [comment] 2019-10-30 08:55
Have the same issues. Any workarounds?

**Comment by romainl** [comment] 2019-10-30 09:22
@RStankov I worked around the issue by rolling back to snapshot 159. I'll wait and see for snapshot 161.

**Comment by ychin** [comment] 2019-10-30 10:20
This will be fixed in snapshot 161 which will come out in a day or so. The cause of this was that snapshot-160 turned on hardened runtime for app notarization requirements but it messed with Python and other scripting languages.

For now, Apple allows using much more lenient restrictions so I'm going to work around the issue and get the app notarized, but they are going to tighten up what they allow to be notarized soon ([Janurary 2020](https://developer.apple.com/news/?id=09032019a)) so I'll need to find a real solution for this problem.

**Comment by ychin** [comment] 2019-10-30 14:05
Fixed in 161

**Closed by ychin** 2019-10-30 14:05 UTC
