### ISSUE TITLE
Vim resizing not working with window snapping tools

### ISSUE THREAD

**Issue by nathom** [macvim-dev/macvim#1195] opened 2021-05-21 16:52 UTC
**Describe the bug**
When using tools like BetterSnapTool or Magnet, which let you snap windows into various sizes, the Vim window size is not conforming to the MacVim window. This leads to the bottom half of the window being unusable. 

The issue doesn't happen when using `mvim --clean`, but it does happen with `mvim` and an empty `.vimrc` file. This probably means the issue is with something automatically loaded by MacVim.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Clean install MacVim
2. Open a new instance of Vim
3. Use a BetterSnapTool, Magnet, or anything similar to snap window to a side. Try this multiple times, dragging the mouse to different locations in the screen.
4. The statusline and command line will be in the middle of the screen.

**Expected behavior**
The Vim window should fill the MacVim window.

**Screenshots**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/74019033/119170675-76337f80-ba18-11eb-9bd1-d40f348909ad.png">

[Screen Recording of Issue (using BetterSnapTool)](https://dropover.cloud/3350f8)

**Environment:**
 - Vim version 8.2, Included patches 1-2681
 - MacOS 11.3.1
 - MacVim GUI

**Additional context**

`mvim --startuptime` logs:
- [With empty .vimrc](https://github.com/macvim-dev/macvim/files/6523964/startup_empty_vimrc.log)
- [With `mvim --clean`](https://github.com/macvim-dev/macvim/files/6523966/startup_clean.log)

**Comment by ychin** [comment] 2021-07-06 22:37
Hi sorry for late response. Since this doesn't happen with `mvim --clean`, do you have any specific guioption or MacVim-specific settings in your vimrc?

Also, can you show me what your MacVim configs are? You can simply run `defaults read org.vim.MacVim | grep MM` and copy the results.

I couldn't quite repro it but it could be due to some difference in configurations we have.

**Comment by nathom** [comment] 2021-07-08 19:14
The output of `defaults read org.vim.MacVim | grep MM`:

```
    MMAppearanceModeSelection = 0;
    MMAutosaveColumns = 177;
    MMAutosaveRows = 45;
    MMCurrentPreferencePane = General;
    MMLastWindowClosedBehavior = 2;
    MMNoTitleBarWindow = 0;
    MMSuppressTerminationAlert = 1;
    MMTitlebarAppearsTransparent = 1;
    MMTopLeftPoint = "{0, 900}";
```

Also, here is my `.gvimrc`:
```
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .gvimrc
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ set macligatures
   2   │ set guifont=FiraCode\ Nerd\ Font:h13
   3   │ "set guifont=SF\ Mono:h13
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────
```

However, after I updated to macOS 12 beta, the issue is no longer there.

**Comment by ychin** [comment] 2022-09-10 23:34
I think I'm going to close this for now. Unfortunately, I could not reproduce this, and seems like it's fixed for you as well. If someone else finds this issue, even if on macOS 11, feel free to comment here and I can re-investigate.

**Closed by ychin** 2022-09-10 23:34 UTC
