### ISSUE TITLE
It has the feeling of flash screen,when there is too much content in one line

### ISSUE THREAD

**Issue by mousesmalltail** [macvim-dev/macvim#941] opened 2019-09-18 09:30 UTC
If there is a lot of content in one line, when scrolling the page with the mouse, this line leaves the page at this time, which will give the user a feeling of jumping out of the window. Is this bug? Because your design is to scroll the page according to each line, if there is too much content in one line, it will cause the feeling of flash screen. I hope you can fix this mistake. Thank you.

**Comment by eirnym** [comment] 2019-09-19 07:15
@mousesmalltail Thank you for an issue

Please, provide more input data. It'll be very helpful if you record the window and attach an animation to the issue. Also I suggest to look into issue #877 to tell if it a possible duplicate.

**Comment by mousesmalltail** [comment] 2019-09-19 09:46
![image](https://user-images.githubusercontent.com/49893345/65232839-6b6a6e00-db04-11e9-910e-50e30a507d9d.png)
![image](https://user-images.githubusercontent.com/49893345/65233454-6f4ac000-db05-11e9-9732-3415a39c1b8a.png)

**Comment by mousesmalltail** [comment] 2019-09-19 09:53
if there is too much content in one line, it will cause the feeling of flash screen. Instead, the user slides the mouse slightly and the line moves up a bit, rather than all content in this line up。

**Comment by mousesmalltail** [comment] 2019-09-19 10:02
![image](https://user-images.githubusercontent.com/49893345/65234693-a621d580-db07-11e9-9955-e400cc6c687f.png)

**Comment by eirnym** [comment] 2019-09-19 10:05
Do I understand correctly, that you're using word wrapping and very long lines and the second line is not shown because the first one is too long? 

Could you please, try also a terminal version of MacVim?

**Comment by mousesmalltail** [comment] 2019-09-19 10:10
Thank you for your reply,My Mac system version is 10.14.4,and my MacVim
version is 8.1.1722


Arseny Nasokin <notifications@github.com> 于2019年9月19日周四 下午6:05写道：

**Comment by mousesmalltail** [comment] 2019-09-19 10:13
yes ,you understand correctly

mouse tail <os119tail@gmail.com> 于2019年9月19日周四 下午6:10写道：

**Comment by eirnym** [comment] 2019-09-19 10:13
thank you, it's important

**Comment by eirnym** [comment] 2019-09-19 10:19
Could you test the same issue in Vim running in terminal?  

How did you installed MacVim? It provides console vim

**Comment by eirnym** [comment] 2019-09-24 16:07
@mengelbrecht I tested your issue on terminal ViM and it seems it just works this way. If you're not happy with this, please, create an issue in [vim/vim](https://github.com/vim/vim)

**Comment by ychin** [comment] 2019-10-08 06:34
@mousesmalltail / @eirnym  Yes, this issue is how Vim scrolls, as it doesn't have a concept of "displaying in the middle of a line".

You could try to do `set display=lastline` which helps display long wrapped lines at the *end* of the screen, but it doesn't help your issue exactly.

Duping this as a dupe of https://github.com/vim/vim/issues/3188. This is an issue with a lot of requests over the years in Vim.

**Closed by ychin** 2019-10-08 06:34 UTC

**Comment by mousesmalltail** [comment] 2020-05-27 03:11
The problem has been solved
