### ISSUE TITLE
Fullscreen in 10.10 (with multiple monitors) has a black bar obscuring the the top of the window.

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#14] opened 2015-05-04 18:01 UTC
_From @GoogleCodeExporter on March 16, 2015 9:25_

```

What steps will reproduce the problem?

open macvim in osx 10.10, toggle the native osx fullscreen function.

What is the expected output? What do you see instead?

Expected that the application would transition to the native OSX fullscreen 
functionality and that the entire window would be visible. Instead, the top of 
the window is obscured by a solid black bar.

Attached before and after screenshots.

What version of MacVim and OS X are you using (see "MacVim->About MacVim"
and  "Apple Menu->About This Mac" menu items, e.g. "Snapshot 40, 10.5.6
Intel")?

Custom Version 7.4 (73), Installed via homebrew.
10.10, Intel


Please provide any additional information below.

I had a similar issue in 10.9, however the bar there was gray instead of black, 
and it was not consistent. This seems to happen every time.
```

Original issue reported on code.google.com by `de...@derekleverenz.com` on 17 Oct 2014 at 10:49

Attachments:
* [before_fullscreen.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-515/comment-0/before_fullscreen.png)
* [after_fullscreen.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-515/comment-0/after_fullscreen.png)

_Copied from original issue: douglasdrumond/macvim#515_

**Comment by douglasdrumond** [comment] 2015-05-04 18:01
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
The first workaround i found is to uncheck "Prefer native full-screen support" 
in preferences.
```

Original comment by `pixel5...@gmail.com` on 18 Oct 2014 at 12:27

Attachments:
* [screen.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-515/comment-1/screen.png)

**Comment by douglasdrumond** [comment] 2015-05-04 18:01
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Oh nice, thanks. That isn�t quite the same but it is a good workaround.
```

Original comment by `de...@derekleverenz.com` on 19 Oct 2014 at 7:32

**Comment by douglasdrumond** [comment] 2015-05-04 18:01
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Just an update, the title specifies multiple monitors, but the problem occurs 
regardless of multiple monitors
```

Original comment by `de...@derekleverenz.com` on 20 Oct 2014 at 3:54

**Comment by douglasdrumond** [comment] 2015-05-04 18:01
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I get the same problem, and also various graphical bugs with the text after 
going into full screen. However, after creating or destroying a screen split, 
everything seems to return to normal. Perhaps you folks should try that.
```

Original comment by `mwill...@gmail.com` on 24 Oct 2014 at 12:38

**Comment by douglasdrumond** [comment] 2015-05-04 18:01
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
By screen-split, do you mean a window (eg C-w v) or (C-w s)? creating and 
destroying them unfortunately doesn't seem to do anything about this problem 
for me. 
```

Original comment by `de...@derekleverenz.com` on 29 Oct 2014 at 6:04

**Comment by douglasdrumond** [comment] 2015-05-04 18:01
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Same problem.
With native full-screen support, I get fullscreen work when zoom it after full 
screen. But MacVim will zoom out when I switch to another application and 
reactivate it by Keyboard Maestro(it is fine by switching), so that is not a 
good workaround.
```

Original comment by `leondo...@gmail.com` on 3 Nov 2014 at 4:11

**Comment by douglasdrumond** [comment] 2015-05-04 18:01
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
patch from separate issue thread helps.
https://code.google.com/p/macvim/issues/detail?id=514&start=100
```

Original comment by `pixel5...@gmail.com` on 3 Nov 2014 at 10:23

**Comment by jpetrie** [comment] 2015-05-04 18:20
This looks like a duplicate of issue #12.

**Comment by McBrainy** [comment] 2015-06-01 19:44
Workaround: After increasing and then decreasing the font size while in full screen mode using <kbd>CMD</kbd>+<kbd>+</kbd> and <kbd>CMD</kbd>+<kbd>-</kbd>, the black bar goes away. This seems to demonstrate that the problem only occurs when entering full screen mode and not when changing the font size while in full screen mode.

**Closed** 2015-11-07 01:51 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
