### ISSUE TITLE
macOS high sierra + lastest release = black screen on fullscreen

### ISSUE THREAD

**Issue by vahvarh** [macvim-dev/macvim#557] opened 2017-10-10 10:48 UTC
macOS high sierra
macvim snapshot 138

screen goes (almost) black, only cursor, tabs and scroller are visible. on moving cursor or editing text, screen is gradually drawn back. 

how to reproduce:
open macvim
go fullscreen
switch to another desktop
switch back to macvim

**Comment by ActionScripted** [comment] 2017-10-10 13:14
I've had this issue also. I've also had this lead to other issues with other windows like text input hovers that only manifest while MacVim is open.

**Comment by alokshenoy** [comment] 2017-10-10 15:34
Same issue here. 
OS: MacOS High Sierra (with Supplemental Update)
MacVim: Snapshot 138 (installed using HomeBrew)
Plugins: YCM, NerdTree, AutoPairs, matchtag, Airline

Reproduction: Same as original post by @vahvarh

**Comment by ZeerakW** [comment] 2017-10-10 17:17
Same issue here.

**Comment by fishioon** [comment] 2017-10-12 13:55
Same issue here.

**Comment by fskirschbaum** [comment] 2017-10-12 17:09
Same. This was happening on intermittently Sierra for me as well, but is now constant on High Sierra  whenever I leave and go back (which I do often). It's maddening. Easiest way to see contents is to switch tabs and having to `gt` `gT` every time I come back to the window...

**Comment by dehesselle** [comment] 2017-10-15 11:07
Same issue here, with another method of reproducing it:
- go fullscreen with MacVim
- go back to window mode

**Comment by mliker** [comment] 2017-10-15 12:06
Same here but only when i open more then one tab. with a single tab open switching back and forth between apps does not corrupt macvim window content

**Comment by ls84** [comment] 2017-10-17 03:33
I can reproduce this by 
* toggle MacVim to fullscreen mode
* activate Mission Control (three finger swipe up by default)
* wait a few seconds, MacVim app thumbnail from the top selection area goes blank
* MavVim becomes black screen

![macvim](https://user-images.githubusercontent.com/7627744/31645502-f3324592-b32e-11e7-8b65-3635c5aab04f.jpg)

**Comment by ZeerakW** [comment] 2017-10-17 14:35
I can confirm that @mliker's fix works (although inelegantly as the default screen toolbar stays on and takes over the top of the window.

**Comment by mliker** [comment] 2017-10-17 14:44
@ZeerakW another workaround is to keep the setting on and only use buffers, not tabs.

**Comment by cvortmann** [comment] 2017-10-20 08:16
It also happens if you're in fullscreen, use MacVim as the git editor and call `git commit`. It'll open another MacVim screen which sometimes is black and/or unresponsive. The fullscreen MacVim will be then black.

**Comment by dmost1** [comment] 2017-10-23 17:23
A resolution I've found, is to just alter the font size, even just one alteration fixes the black screen, then one can negate the alteration and be back to their original configuration. A bit of a hassle, though.

**Comment by dmost1** [comment] 2017-10-23 17:36
I'm not positive, but I believe it has to do with increasing font size. When I have mvim open on default font settings, and full screen, there's no black screen. However, after altering the font size, and using the above methods of reproduction, such as mission control, or changing desktops, the black screen issue occurs. Once on the black screen changing the font size, even one increment, fixes the black screen issue.

**Comment by splhack** [comment] 2017-10-26 05:33
Could you guys try this with Core Text renderer?

    $ defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES

**Comment by dmost1** [comment] 2017-10-26 15:20
@splhack I can confirm that after issuing that command, "Use Core Text Renderer", can be enabled, and there is no more error on my end.

**Comment by alokshenoy** [comment] 2017-10-26 15:40
@splhack: what exactly is MMUseCGLayersAlways?

**Comment by splhack** [comment] 2017-10-26 15:52
@dmost1 what do you mean by "errors"? No more black screen with `MMUseCGLayerAlways=YES`?

@alokshenoy see https://github.com/macvim-dev/macvim/blob/master/src/MacVim/MMCoreTextView.m

**Comment by dmost1** [comment] 2017-10-26 15:55
@splhack Yes, I should retract that. There is no more error, that being the black screen error, which I was having prior to issuing the 

`$ defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES
`

**Comment by splhack** [comment] 2017-10-27 03:48
Again. Could you guys try this with Core Text renderer?

    $ defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES

**Comment by fskirschbaum** [comment] 2017-10-27 08:49
`defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES` seems to correct issue for me, @splhack. Thank you!

**Comment by alokshenoy** [comment] 2017-10-28 16:23
@splhack Resolved it for me too.

**Comment by splhack** [comment] 2017-10-28 22:29
Updated FAQ https://github.com/macvim-dev/macvim/wiki/FAQ#black-screen-on-full-screen

**Comment by dehesselle** [comment] 2017-10-29 00:37
May I politely ask if documenting the workaround in the FAQ is supposed to be the final solution to this issue? I would either expect the underlying issue to be resolved with a future release of MacVim, or, if I am mistaken to call the current solution a workaround, expect a future release of MacVim to ship with adjusted default settings to accommodate for the necessary changes.

I cannot tell from reading the FAQ if this is meant as a temporary solution or not. I'm hoping you're not going to leave it as it is right now, MacVim in a broken state (no offense, I know very well that the new OS broke it), relying on the user to fix it.

**Comment by splhack** [comment] 2017-10-29 01:27
will reopen this but I have been not able to repro this at all, so no further action from my end.

**Comment by dehesselle** [comment] 2017-10-29 09:52
@splhack Thank you for your efforts so far! I think leaving this open is the best course of action for now. 

Also, very valuable information from your end: you're the first one to report here who cannot reproduce this issue. That leads to me believe that we've got dig a little deeper. What kind of Mac do you have? Is this possibly a retina vs non-retina issue? I was at a friend's yesterday (non-retina Macbook), no issue there as well.

**Comment by vahvarh** [comment] 2017-10-29 12:58
I have a problem on macbook air 2014 + apple thunderbolt display.
I think that has nothing to do with retina.

"defaults write" solves for me.

**Comment by dmost1** [comment] 2017-10-29 13:52
I also agree that I believe it doesn't have to do with Retina. My mac air doesn't have one, and it did produce the black screen error, initially, before the quick fix.

**Comment by vahvarh** [comment] 2017-11-07 06:47
after quick fix and on latest version, there is no black screen but when I start editing (prior to changing to another tab and back), screen gets messed up.

**Comment by ZeerakW** [comment] 2017-11-09 18:04
Just updated to the latest High Sierra version which seems to have fixed the issue for me (without defaults.write).

**Comment by eaoliver** [comment] 2017-11-10 02:20
I can reproduce the blank screen, while `defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES` is set.

I open a mvim window on an external display, make it full screen, and then invoke mvim again.  In settings, I open files from applications 'in a new window'; however, mvim is opening a new tab that is full black.  When mvim is not in full screen mode, the behaviour is as expected (new window for new files).

**Comment by kamyuentse** [comment] 2017-11-21 06:24
Same issue here.

After applying the command `defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES`,
the following issue happened
<img width="440" alt="screen shot 2017-11-21 at 2 23 27 pm" src="https://user-images.githubusercontent.com/15538025/33057805-9bddd644-cec7-11e7-9ea0-93d6a1e4ec8c.png">

**Comment by StaverDmitry** [comment] 2017-11-26 22:55
After applying the command `defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES`
my macvim's scrolling became insanely slow, I know you're not supposed to scroll using vim indeed, but when I just try to move a few lines lower I experience a pretty big delay.
mbp 2017 high sierra

**Comment by tlindteigen** [comment] 2017-12-10 19:32
If you are using multiple monitors, want to edit in full screen, and want to leave Core Text renderer enabled, then the change that worked for me: goto MacVim->Preferences->Advanced
- Check "Use Core Text renderer"
- Uncheck "Prefer native full-screen support"

I did not need `defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES`, which seemed to create additional rendering problems since I wanted to leave "Use Core Text renderer" enabled for performance reasons.

**Comment by jonathanpatt** [comment] 2017-12-22 17:02
This issue makes MacVim nearly unusable for me in a work environment. The solution should not be a hack to get around it by disabling Core Text and suffering from performance loss as a result.

**Comment by sasha-alias** [comment] 2018-01-06 17:36
Disabling Core Text renderer brings another set of issues :(
I found a very radical workaround: migrate to neovim + VimR as a GUI

**Comment by blochberger** [comment] 2018-01-26 14:04
This might be related to #196.

**Comment by rspenc29** [comment] 2018-02-26 14:57
> $ defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES

This fixes the black screen issue but breaks my cursor.

**Comment by imajes** [comment] 2018-02-26 15:23
Hey, this doesn't solve the problem of my macvim; when resizing to max it still shows no UI.

**Comment by MadWombat** [comment] 2018-03-13 19:26
+1 on the problem. Setting `defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES` causes rendering issues similar to the screen grab posted by @kamyuentse. Unchecking "Prefer native full-screen support" as suggested by @tlindteigen causes the app launcher bar to always stay above the window.

**Comment by kibiz0r** [comment] 2018-04-19 15:25
How are you guys even unchecking "Prefer native full-screen support"? My preference window is just a white box.

Screenshot:
<img width="1041" alt="screen shot 2018-04-19 at 11 24 34" src="https://user-images.githubusercontent.com/118859/39001444-5000518a-43c4-11e8-8b0c-d3a17d9bbd0d.png">

**Comment by pablinos** [comment] 2018-04-20 16:16
The `defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES` fix seemed to work for me. It's early days though. There might be something else that goes wrong!

Sounds like it could be a plugin issue, especially as it's affecting different people in different ways. I haven't got any of the plugins mentioned above installed though. Python problem maybe?!?

**Comment by lsnizek** [comment] 2018-04-24 11:48
`MMUseCGLayerAlways` fixed black patches in macOS full screen when multiple tabs are open or view is split. Both _User Core Text renderer_ and _Prefer native full-screen support_ are enabled.

**Comment by ZeerakW** [comment] 2018-05-01 23:02
Tried commenting out the entire vimrc but unfortunately, no luck on my end. Also tried removing python2 and running a clean install but no dice.

**Comment by fftyjw** [comment] 2018-06-07 10:43
autocmd FocusLost * redraw!
works for me

**Comment by zoerb** [comment] 2018-06-28 16:09
Here's a minimal repro with a stock MacVim install (no plugins or custom vimrc).  This is using the latest MacVim snapshot (149), with core text and native full-screen enabled, and without changing MMUseCGLayerAlways from its default.

Start MacVim, enter full-screen, **create a new window split**, then either switch macOS spaces or enter mission control, and return to the MacVim space.  For me it shows a black screen.  Note that I don't see the black screen if I don't create a window split, or if I create the window split *before* entering full-screen.  Calling :redraw! fixes rendering, but creating a new window and switching spaces surfaces the issue again.

**Comment by maggyero** [comment] 2018-10-25 05:58
Same black fullscreen issue on the new macOS Mojave (10.14) with macVim 8.1.280:

1. Open macVim.
2. Go fullscreen.
3. **Open a new tab.**
4. Switch to another screen.
5. Switch back to macVim.

Note that you have to open a new tab _in fullscreen mode_ to trigger the issue (tabs open in normal mode do no harm).

**Comment by peterwillcn** [comment] 2018-11-01 06:50
I've had this issue also MacOS Mojave 10.14

**Closed** 2018-11-02 05:33 UTC

**Comment by mereddy22** [comment] 2018-11-02 15:52
I bought a new MacBook Pro 15 inches last week and installed macvim on mac latest os but it is acting weird like mvim screen is blinking and sometimes goes completely black image and I tried uninstall and installed several times but the issue is not resolved.

Could someone please help me how to fix

Thanks

**Comment by ychin** [comment] 2018-11-02 15:56
@mereddy22 I believe that's #751. We are currently trying to fix it and there is a pull request under review right now and should be merged in soon.

How are you installing MacVim? If you use the official release from this site it should not have the issue (since it's still being built with High Sierra SDKs). Or are you using it from Homebrew?

**Comment by mereddy22** [comment] 2018-11-02 16:02
@ychin using Homebrew I installed macvim on my system

**Comment by philipn** [comment] 2018-11-19 23:05
Could a build be made available that includes these fixes?  Does homebrew include them?

**Comment by ychin** [comment] 2018-11-20 05:00
Homebrew build includes that already. For the binary snapshot releases here on Github I think I would prefer to make a release containing the fix for all the Mojave issue as well, unless that drags on too much.
