### ISSUE TITLE
[Regression, minor] Visual defect in MacVim preferences

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#1039] opened 2020-04-13 08:26 UTC
**Describe the bug**
MacVim preferences tab transition makes labels overlap over themselves for a second

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`  (doesn't really matter)
2. Open preferences (Cmd-,)
3. Switch tabs

you have at least a second to look at this mess

**Expected behavior**
Transition is fast and smooth, like Safari or Mail, or System Settings (as it was before)

**Screenshots**
<img width="1680" alt="Zrzut ekranu 2020-04-13 o 10 13 45" src="https://user-images.githubusercontent.com/485399/79105375-d1546680-7d70-11ea-9d7a-022abb0de2ff.png">

**Environment (please complete the following information):**
 - MacVim 163 from GitHub 
 - macOS 10.15.4 (19E287)
 
**Additional context**
defaults:

```sh
$ defaults read org.vim.MacVim | grep 'MM\|SU'
    MMAutosaveColumns = 150;
    MMAutosaveRows = 59;
    MMCurrentPreferencePane = General;
    MMRenderer = 1;
    MMTitlebarAppearsTransparent = 1;
    MMTopLeftPoint = "{1025, 1010}";
    "NSWindow Frame SUUpdateAlert" = "530 487 620 392 0 0 1680 1027 ";
    SUCheckAtStartup = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-04-13 08:12:05 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 4120494361;
    SUUpdateRelaunchingMarker = 0;
```

**Comment by ychin** [comment] 2020-04-14 07:26
I'm confused. What has regressed? This is how preference panel in MacVim has worked for like years. It's a minor issue for sure, but I'm not sure why it was tagged as "regression".

The PR you are looking at (#1038) in fact turns off that cross-fade anyway so it will go away next release.

**Comment by ychin** [comment] 2020-04-15 05:47
Anyway, closing this issue because either way it should be fixed in the latest change that will be released in 164.

**Closed by ychin** 2020-04-15 05:47 UTC

**Comment by eirnym** [comment] 2020-04-15 19:39
I haven't seen this ever in MacVim, but thanks
