### ISSUE TITLE
Release 8.0.1272 compiled without ruby support

### ISSUE THREAD

**Issue by vnazarenko** [macvim-dev/macvim#600] opened 2017-11-20 21:11 UTC
Hello. after updating to latest mvim Custom Version 8.0.1272 (142), 
commend-t plugin stop to work, because of 
command-t.vim requires Vim to be compiled with Ruby support

**Comment by splhack** [comment] 2017-11-20 21:13
Duplicate of #598

**Closed by splhack** 2017-11-20 21:13 UTC
