### ISSUE TITLE
Full screen is much slower.

### ISSUE THREAD

**Issue by jordwalke** [macvim-dev/macvim#665] opened 2018-03-31 09:22 UTC
I noticed that full screen is much slower in recent releases even back as far as six months ago or more.
It didn't use to be the case I believe. It is noticeable when scrolling line by line.

(Note: I do not use "native full screen").

**Comment by chdiza** [comment] 2018-03-31 12:29
I use non-native fullscreen all day, every day, and have noticed no slowdowns whatsoever.

My guess is that Vim's silly `defaults.vim` setup inserted some setting that you used to not have set, and that's causing it.  Or that a syntax file that you use frequently got changed and is now slower.  Or that some plugin is doing resource-intensive things.

Does it happen with `mvim -u NONE -U NONE -N --noplugin`?

**Comment by amadeus** [comment] 2018-04-04 19:53
I bet it's related to this issue - https://github.com/macvim-dev/macvim/issues/499

On retina screens the renderer really chugs. It's not super noticeable on a macbook screen at default resolution, but if it's a big retina screen, it totally tanks.

**Comment by ychin** [comment] 2018-12-20 09:18
Closing this as it's a duplicate of #499.

See https://github.com/macvim-dev/macvim/issues/499#issuecomment-448927102 for rationale for closing.

**Closed by ychin** 2018-12-20 09:18 UTC
