### ISSUE TITLE
Window navigation working only for the first one

### ISSUE THREAD

**Issue by javiyu** [macvim-dev/macvim#692] opened 2018-06-15 09:32 UTC
Version 8.0.1633 (146)

I have vim windows open (one per tab), in the first one navigation is working but in the other ones is not.

Window menu for the first one:

![captura de pantalla 2018-06-15 11 10 58](https://user-images.githubusercontent.com/83056/41460394-dcad4da0-708c-11e8-8d80-ef93e84f03c7.png)

Window menu for the rest:

![captura de pantalla 2018-06-15 11 11 09](https://user-images.githubusercontent.com/83056/41460403-e4766ae4-708c-11e8-8574-eddbf135ee17.png)

It may be more problems with the menu because 'Enter full screen' appears many times

**Comment by ychin** [comment] 2018-12-12 08:48
I'm closing this because the "window navigation" menu items that you mentioned are all related to High Sierra's native tabs, which MacVim doesn't work properly with. I have since turned off native tabs explicitly in the app so you would not see those menu items at all (e.g. "Merge All Windows") in any windows now. If you want that feature use #544 for tracking.

The "Toggle Full Screen Mode" issue is a duplicate of #566.

**Closed by ychin** 2018-12-12 08:48 UTC
