### ISSUE TITLE
:terminal display bug

### ISSUE THREAD

**Issue by mihaicristiantanase** [macvim-dev/macvim#594] opened 2017-11-13 09:13 UTC
**:terminal display bug**

### Bug:
When I run:
> cat /tmp/test-file.txt

in a ":terminal" window, the output is not identical to the file content (shows partial lines,
or consecutive lines combined with each other).

### Demo:
![macvim-terminal-output-bug](https://user-images.githubusercontent.com/7289591/32717731-6d02ac4c-c863-11e7-9934-59107c407da9.gif)

### Test details:

/tmp/test-file.txt is structured this way:
>This is a test line with data: 1
...................................
This is a test line with data: 2156
This is a test line with data: 2157
...................................
This is a test line with data: 4311

### System Details:
> MacVim 8.0.1272
> macOS Sierra 10.12.1 (16B2555)

### Observations:
The following command retuns the correct result:
> cat /tmp/test-file.txt | grep "^This is a test line with data:" | wc -l

**Comment by semanser** [comment] 2017-12-01 19:04
Possible duplicate of #579

**Comment by mihaicristiantanase** [comment] 2017-12-02 03:25
Yes, it does seem to be the same issue.

**Comment by splhack** [comment] 2017-12-07 06:23
duplicate of #579

**Closed by splhack** 2017-12-07 06:23 UTC
