### ISSUE TITLE
MacVim crashes when se/set command issued without arguments

### ISSUE THREAD

**Issue by LukeOrgana** [macvim-dev/macvim#431] opened 2016-12-05 06:28 UTC
I have MacVim (8.0) installed on macOS Sierra (10.12).

I have incorporated functionality into my .vimrc file to automatically save my session in ~/.vim/sessions when closing (session name can be set using :SetSession "session_filename", or if not set it is automatically saved as LastSession.vim). This works fine if I am working in a C++ project. However, I have just installed vim-latex and now when editing a latex file the save/open session functionality does not work. When closing Vim, no session file is created automatically. If I create one manually using :mksession! path/to/sessions/sessionfilename.vim, then the file is created as expected but loading this file from within Vim causes Vim to crash. I have carried out some simple debugging and it crashes upon issuing the :se[t] command without any arguments, which appears on the final line of the sessionfilename.vim file when I am working with .tex files. I have further examined this issue by just entering in the :se command on its own in Vim and it causes my MacVim window to shut down instantly, regardless of what file I am editing (cpp/tex/whatever).

I have attached my .vimrc file (which I have had to rename as vimrc.txt to upload here) and the output from running :so $VIMRUNTIME/bugreport.vim. Also included are two debug logs (renamed with .txt extension in order to upload). The first of these was when I attempted to load a saved session straight away after MacVim started. The second was when I manually loaded a .tex document, and then entered the command :set. Both of which resulted in the terminal output:

`Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault: 11`

[macvim.log.txt](https://github.com/macvim-dev/macvim/files/630254/macvim.log.txt)
[macvim1.log.txt](https://github.com/macvim-dev/macvim/files/630255/macvim1.log.txt)
[vimrc.txt](https://github.com/macvim-dev/macvim/files/630236/vimrc.txt)
[bugreport.txt](https://github.com/macvim-dev/macvim/files/630237/bugreport.txt)

**Comment by chdiza** [comment] 2016-12-05 15:39
Since :set without arguments does not crash MacVim started with `mvim -u NONE -U NONE -N` on my machine, the problem is with one of your plugins.

**Comment by splhack** [comment] 2016-12-06 17:55
@LukeOrgana Can you share the crashlog under ~/Library/Logs/DiagnosticReports? And can you repro this issue in the latest Vim? You can install `brew install vim` using http://brew.sh/ , or via your favorite package manager.

**Comment by clamey** [comment] 2016-12-07 17:28
I'm getting crashes on `:set` when I start with `mvim -u NONE -U NONE -N`

I have also moved $HOME/.vimrc, $HOME/.gvimrc, and $HOME/.vim out of the way, so I don't think it's my setup (any help would be appreciated).

I have done `brew update && brew upgrade && brew install vim`

[bugreport.txt](https://github.com/macvim-dev/macvim/files/637296/bugreport.txt)

[Vim_2016-12-07-101531_gnathic.crash.txt](https://github.com/macvim-dev/macvim/files/637289/Vim_2016-12-07-101531_gnathic.crash.txt)

**Comment by splhack** [comment] 2016-12-07 17:47
@clamey can you confirm these?
- MacVim snapshot-117: `mvim -u NONE -U NONE -N` -> `:set` -> crash
- Vim homebrew latest: `vim -u NONE -U NONE -N` -> `:set` -> don't crash

**Comment by clamey** [comment] 2016-12-07 17:51
Yes - mvim crashes on :set, /usr/local/bin/vim does not:

```
 clamey  gnathic  ~  $  mvim -u NONE -U NONE -N
 clamey  gnathic  ~  $  Vim: Caught deadly signal SEGV
Vim: Finished.

 clamey  gnathic  ~  $  vim -u NONE -U NONE -N
 clamey  gnathic  ~  $  which vim
/usr/local/bin/vim
 clamey  gnathic  ~  $ 
```

**Comment by splhack** [comment] 2016-12-07 20:33
Fixed in 1de4548643335b10b5759642c3594f2fc976cab1

**Closed by splhack** 2016-12-07 20:33 UTC

**Comment by clamey** [comment] 2016-12-08 16:42
Fix verified in 118 - thanks!

**Comment by LukeOrgana** [comment] 2016-12-09 02:28
Sorry. I was insanely busy at work and didn't have time for much else. I guess you don't need the crash report any more? Thanks.
