### ISSUE TITLE
Update offers v8.0 as upgrade from v8.1.235

### ISSUE THREAD

**Issue by sloanlance** [macvim-dev/macvim#733] opened 2018-08-21 15:39 UTC
MacVim (Custom Version 8.1.235 (150)) is offering v8.0 as an update.  See screenshot below, since the UI wouldn't allow me to copy the text.

<img width="732" alt="screen shot 2018-08-21 at 11 36 11" src="https://user-images.githubusercontent.com/17595351/44412392-d549ca00-a536-11e8-9972-b7fb39f6e60d.png">

**Comment by jpetrie** [comment] 2018-08-23 03:38
It's actually offering you 8.1.280. There are some display issues with the number formatting in this UI. This is a duplicate of #694.

**Closed by jpetrie** 2018-08-23 03:38 UTC
