### ISSUE TITLE
With the latest release, FPS scrolled down

### ISSUE THREAD

**Issue by nooks** [macvim-dev/macvim#819] opened 2018-12-14 14:41 UTC
macOS 10.14.1
MacBook Pro (Retina, 15-inch, Mid 2014)
Intel Iris Pro 1536 МБ

**Comment by ychin** [comment] 2018-12-15 21:13
Sorry I didn't quite understand from your descriptions. Are you saying the frame rate when scrolling down is slow? How slow? Are you using the GUI version? Are you using Mojave?

**Comment by ychin** [comment] 2018-12-22 08:47
Closing as duplicate of #796

**Closed by ychin** 2018-12-22 08:47 UTC
