### ISSUE TITLE
MacVim + Catalina vsp window does not properly align

### ISSUE THREAD

**Issue by ruckserve** [macvim-dev/macvim#969] opened 2019-10-22 18:54 UTC
**Describe the bug**
The vertical split functionality seems to be broken since I updated Vim with Catalina installed. The line, rather than appearing as a solid vertical split, seems to flow around the text in the lefthand buffer

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `mvim --clean -O <any 2 non empty filenames>`
2. The vertical split bar will flow around the file on the left hand side, not a straight line as you would expect

**Expected behavior**
The normal VSP line in the middle would be a straight line

**Screenshots**
![image](https://user-images.githubusercontent.com/6752293/67319062-083c7480-f4d2-11e9-8e34-d1a98436675a.png)

**Environment (please complete the following information):**
 - Vim version - 8.1.2198
 - OS: Catalina [10.15 (19A602)]
 - Terminal: GUI

**Additional context**
I have tried this with default brew installed macvim as well as running `brew unlink macvim && brew install macvim --HEAD`. I believe this is related to https://github.com/macvim-dev/macvim/issues/949 though only because of when this manifested, I have not plumbed the xcode diffs in xcode 11

**Comment by eirnym** [comment] 2019-10-22 18:57
@ruckserve thank you for an issue

Could you please try the terminal version of MacVim?

**Comment by eirnym** [comment] 2019-10-22 18:59
BTW, I can't reproduce it with snapshot 159 from GitHub (Homebrew has the latest version correctly applied, so it safe to use it)

**Comment by ruckserve** [comment] 2019-10-22 19:53
I'm not sure what you mean by
> terminal version of macvim
I can open vim on the terminal but it's just my homebrew installed vim (/usr/local/bin/vim), and that works correctly with `:vsp`. If I open mvim or gvim I get a GUI window.

**Comment by eirnym** [comment] 2019-10-22 20:19
Open not in gui, but terminal. When you install `MacVim`, it provides `vim` and `gvim` scripts as well.

**Comment by eirnym** [comment] 2019-10-22 20:20
and please check the latest build (not `HEAD` as you proposed above)

**Comment by ychin** [comment] 2019-10-23 09:05
To open MacVim in terminal mode, easiest way is `mvim -v`.

I think the issue is the GUI's text renderer though. @ruckserve do you have CoreText renderer enabled/disabled? Easiest way is to follow instructions at https://github.com/macvim-dev/macvim/wiki/Reporting-an-Issue and do the following and paste the results here:

    defaults read org.vim.MacVim | grep 'MM\|SU'

**Comment by eirnym** [comment] 2019-10-23 19:47
@ychin juste tested it. I reproduced the issue with CTR disabled.

**Comment by ruckserve** [comment] 2019-10-24 22:35
Thanks @ychin and @eirnym. Sorry for the delay, I'll check the docs for how to enable the CTR and see if that fixes it.

**Comment by ruckserve** [comment] 2019-10-24 22:40
Ok, I checked the `Use Core Text renderer` in the Preferences menu, restarted macvim and the issue has gone away. Thanks for the help, I'll leave this issue open for the fix but use the CTR going forward if that is the preferred usage. Thanks again

**Comment by eirnym** [comment] 2019-10-28 20:59
@ychin, Please, include all important information into template, it'll be easier to follow it rather than reading a wiki

**Comment by ychin** [comment] 2020-09-21 05:35
I'm closing this issue because Core Text Renderer should be on at all times. The non-CTR option is essentially deprecated (future versions' UI will make that clear). We should just focus on making the main renderer better instead of supporting a deprecated legacy renderer.

**Closed by ychin** 2020-09-21 05:35 UTC
