### ISSUE TITLE
An uncaught exception with full screen code

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#62] opened 2015-07-22 11:16 UTC
OS X El Capitan gives nice traces on uncaught exceptions. I don't know if this applicable with Yosemite, but may be a clue for fixing issues.

MacVim Snapshot 77
OSX El Capitan 10.11

With MacVim and full screen I've got following exception trace:
```
2015-07-22 13:35:14.476 MacVim[3732:2892587] *** Assertion failure in -[_NSWindowFullScreenTransition startExitFullScreenTransitionForCGWindow:targetFrame:duration:completionHandler:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1386.12/AppKit.subproj/NSWindowFullScreenTransition.m:604
2015-07-22 13:35:14.479 MacVim[3732:2892587] An uncaught exception was raised
2015-07-22 13:35:14.479 MacVim[3732:2892587] Invalid parameter not satisfying: _fullScreenState == NSExitingFullScreen
2015-07-22 13:35:14.479 MacVim[3732:2892587] (
	0   CoreFoundation                      0x00007fff8c9c7b5c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8d19a8e8 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8c9c793a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff85c32bcc -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   AppKit                              0x00007fff87d38a03 -[_NSFullScreenTransition startExitFullScreenTransitionForCGWindow:targetFrame:duration:completionHandler:] + 168
	5   AppKit                              0x00007fff87d3894e -[_NSWindowFullScreenTransition _exitFullScreenModeForWindow:duration:completionHandler:] + 185
	6   AppKit                              0x00007fff88222c87 NSPerformVisuallyAtomicChange + 147
	7   AppKit                              0x00007fff88335541 __106-[_NSWindowFullScreenTransition _performExitFullScreenModeForWindow:options:customWindows:doKitAnimation:]_block_invoke + 668
	8   AppKit                              0x00007fff8824e288 __177-[NSDockConnection(FullScreenMessages) sendFullScreenExitForTransition:synchronous:window:exitForClose:backgroundWindows:participatingWindows:customAnimation:completionHandler:]_block_invoke + 60
	9   libxpc.dylib                        0x00007fff8ba6fcfb _xpc_connection_reply_callout + 26
	10  libxpc.dylib                        0x00007fff8ba6fc9c _xpc_connection_call_reply + 36
	11  libdispatch.dylib                   0x00007fff91350c11 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00007fff91361fdc _dispatch_main_queue_callback_4CF + 1677
	13  CoreFoundation                      0x00007fff8c90ec19 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00007fff8c8c97cd __CFRunLoopRun + 1949
	15  CoreFoundation                      0x00007fff8c8c8dc8 CFRunLoopRunSpecific + 296
	16  HIToolbox                           0x00007fff8c45ba59 RunCurrentEventLoopInMode + 235
	17  HIToolbox                           0x00007fff8c45b6f7 ReceiveNextEventCommon + 184
	18  HIToolbox                           0x00007fff8c45b62f _BlockUntilNextEventMatchingListInModeWithFilter + 71
	19  AppKit                              0x00007fff87a8779c _DPSNextEvent + 945
	20  AppKit                              0x00007fff87e555c9 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 343
	21  AppKit                              0x00007fff87a7d6dc -[NSApplication run] + 682
	22  AppKit                              0x00007fff879ffb6d NSApplicationMain + 1176
	23  libdyld.dylib                       0x00007fff887b05ad start + 1
	24  ???                                 0x0000000000000003 0x0 + 3
)
```

**Comment by eirnym** [comment] 2015-07-23 22:41
I think this is related to Yosemite fullscreen bugs

**Comment by ericcong** [comment] 2015-10-03 17:11
+1, got this bug when trying to exit split-screen.

**Comment by wulh** [comment] 2015-10-04 03:35
+1, encounter this when i quit Mac Vim

**Comment by nguyengiangdev** [comment] 2015-10-06 16:20
Thanks @wulh , i have same prolem.

**Comment by Arnoldnuo** [comment] 2015-10-08 02:21
Thanks @wulh ,I have same problem, and It is fixed after closing "Prefer native full-screen support".

**Comment by splhack** [comment] 2015-11-22 05:51
Have you guys tried the issue on OS X 10.11.1? I can't reproduce it anymore.

**Comment by splhack** [comment] 2015-11-23 02:03
It seems OS X 10.11 issue.

**Closed by splhack** 2015-11-23 02:03 UTC

**Comment by chdiza** [comment] 2015-11-23 03:12
I never could reproduce this on 10.11.
