### ISSUE TITLE
Menubar went black

### ISSUE THREAD

**Issue by jeffzemla** [macvim-dev/macvim#809] opened 2018-12-09 23:24 UTC
In the newest version (152) on macOS 10.12.6, the titlebar went black. Occasionally all of the text will go black, but 'select all' will fix it. I downgraded to 150 and it works fine.

<img width="770" alt="screenshot 2018-12-08 21 26 12" src="https://user-images.githubusercontent.com/3850397/49704315-2a3d4900-fbd7-11e8-937f-f1c29bbeba88.png">

**Comment by ychin** [comment] 2018-12-09 23:42
Duplicate of #799. Will be fixed soon, track it using https://github.com/macvim-dev/macvim/milestone/1.

**Closed by ychin** 2018-12-09 23:42 UTC
