### ISSUE TITLE
fail to install python 2.7.x using pyenv with PYTHON_CONFIGURE_OPTS

### ISSUE THREAD

**Issue by Claudius42** [macvim-dev/macvim#516] opened 2017-06-24 12:21 UTC
I followed the guide https://github.com/macvim-dev/macvim/wiki/Python-2.x-and-Python-3.x and successfully installed python 3.6.0 with the described PYTHON_CONFIGURE_OPTS. However, when I try several versions of python 2.7.x with the PYTHON_CONFIGURE_OPTS it fails (see attached logs).
Only when I just execute 'pyenv install 2.7.10' it successfully installs 2.7.10 but then the lib 'libpython2.7.dylib' is missing.
[consoleLog_trials.txt](https://github.com/macvim-dev/macvim/files/1099680/consoleLog_trials.txt)
[python-build.20170624111221.2017.log.txt](https://github.com/macvim-dev/macvim/files/1099683/python-build.20170624111221.2017.log.txt)
[python-build.20170624111434.9307.log.txt](https://github.com/macvim-dev/macvim/files/1099682/python-build.20170624111434.9307.log.txt)
[python-build.20170624111612.16361.log.txt](https://github.com/macvim-dev/macvim/files/1099681/python-build.20170624111612.16361.log.txt)

Does anyone have any clue what needs to be done?

**Comment by eirnym** [comment] 2019-04-01 22:09
You don't need to recompile it with different Python2.7 builds. It's enough to set `pythonhome` and `pythondll` to the specific env as required.

**Comment by eirnym** [comment] 2019-05-18 10:08
@ychin duplicate of #760

**Comment by eirnym** [comment] 2019-06-13 16:20
@Claudius42 does it still an issue for you?

**Comment by ychin** [comment] 2019-06-17 01:44
Closing as duplicate of #760. Please see that thread @Claudius42. I will need to clean up the wiki page to avoid misleading people. Thanks @eirnym.

**Closed by ychin** 2019-06-17 01:44 UTC
