### ISSUE TITLE
Changing syntax highlighting is broken in MacVim GUI

### ISSUE THREAD

**Issue by Robert-van-Engelen** [macvim-dev/macvim#1304] opened 2022-10-06 18:32 UTC
### Steps to reproduce

1. Select: Syntax -> Show File Types in Menu
2. Select: Syntax -> AB -> Assembly -> Turbo
3. "Error detected while compiling function SetSyn"
4. "E114: Missing quote: " do not replace the filetype but add whitespace on top"

### Expected behaviour

Syntax highlighting changed.

### Version of Vim and architecture

9.0.472, GUI, arm64 included patches 1-472

### Environment

MacOS 12.5.1

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [X] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment] 2022-10-06 22:49
I think that was fixed in upstream Vim in https://github.com/vim/vim/issues/11278 recently. It will be pushed out in the next MacVim release which is probably end of October. For now you probably have to use `set ft` directly.

**Comment by ychin** [comment] 2022-10-06 22:50
Closing for now as the issue is already fixed and merged into macvim. It will be in r175 as I mentioned.

**Closed by ychin** 2022-10-06 22:50 UTC
