### ISSUE TITLE
Paste in :terminal ignored / not passed

### ISSUE THREAD

**Issue by dezza** [macvim-dev/macvim#588] opened 2017-11-09 14:26 UTC
I tried different things like `CMD+V`, entering normal mode with `<C-W>N` and try to paste using `p` nothing works.

I tried with console vim (`mvim -v`) and that works. So it's definetily a loose end in MacVim GU compared to other distributions. Any specific code for :terminal in MacVim GUI or is it related to another thing? Give an answer I might take a look. Weird that only this kind of buffer has with clipboard problems. My Mac is at work so I will not be able to see the value of clipboard if this could have been setlocal for this buffer.

**Comment by ychin** [comment] 2018-10-24 06:10
This is a duplicate of #676 and can be closed (see https://github.com/macvim-dev/macvim/issues/676#issuecomment-432525099).

**Closed** 2018-11-01 07:57 UTC
