### ISSUE TITLE
:vimgrep doesn't work in some cases

### ISSUE THREAD

**Issue by akulakov** [macvim-dev/macvim#887] opened 2019-04-26 01:02 UTC
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
:vimgrep sometimes fails to find simple patterns (no special or escape chars) which is clearly in the file, and is found using normal grep. 

**To Reproduce**
Detailed steps to reproduce the behavior:
Not sure because not consistent. When the buffer where actual valid match is located is reloaded, vimgrep starts finding it again. This makes me think vimgrep may be searching current state of buffer instead of files on disk (which help vimgrep states)

**Expected behavior**
Searched-for pattern is found e.g. 'entries' (with no quotes).

**Environment (please complete the following information):**
 - Vim version MacVim 8.1 1-950
 - OS: macOS 10.12.6]

**Additional context**
Again the key to the bug seems to be that once the buffer is reloaded, vimgrep seems to always find the pattern it was missing before.

**Comment by eirnym** [comment] 2019-04-26 15:28
Does this reproducible with the same/latest Vim version? If yes, please, address your issue there.

**Comment by ychin** [comment] 2019-04-28 05:42
As @eirnym said, this seems like a general Vim issue and it's better if you file there (https://github.com/vim/vim/issues). You may want to be a little more specific in the search command though, as in the exact Ex command you use, as it could be from a misunderstanding of how `vimgrep` works.

**Comment by ychin** [comment] 2019-05-14 08:21
I'm closing the issue due to lack of more information. As I said, this seems more like a core Vim issue so it may fit better there. @akulakov feel free to re-open if you disagree.

**Closed by ychin** 2019-05-14 08:21 UTC
