### ISSUE TITLE
MacVim Release 155 appears to be broken

### ISSUE THREAD

**Issue by flaugher** [macvim-dev/macvim#865] opened 2019-02-20 22:50 UTC
I just now was prompted by MacVim to upgrade to the latest release.  When I allowed MacVim to perform the update and restart, I immediately began getting the following errors when I tried to enter using insert mode:

`
Error detected while processing function <SNR>49_HighLightEOLWhitespaceExceptionCurrentLine:
line   1:
E461: Illegal variable name: a:exclude_current_line_eol_whitespace_pattern
Press ENTER or type command to continue.
`

I have MacVim 8.1.950 (155) running on macOS 10.12.6.

**Comment by ychin** [comment] 2019-02-22 06:36
I couldn't reproduce this. I searched online and seems like you are using https://github.com/ntpeters/vim-better-whitespace? I downloaded the plugin and it still works fine.

The variable (`exclude_current_line_eol_whitespace_pattern`) that your logs show seems to indicate it's an old build as it was removed in https://github.com/ntpeters/vim-better-whitespace/pull/100. I would suggest updating the plugin and/or re-downloading it.

If the issue persists, try running MacVim with `mvim -u NONE -U NONE` (in general it's a good idea to do so to help isolate problems) and that fixes the problem, you may want to file the issue with the plugin's repo.

**Comment by ychin** [comment] 2019-02-22 06:45
Looking more into it I'm pretty sure you just need to update your plugin. Vim has recently introduced a new behavior that tightened the restrictions on writing VimScript, and you can no longer assign to `a:` variables. The older version of the plugin has a bug of writing to `a:` that gets exposed in the new version of Vim.

If you can confirm the new version of the plugin fixes the issue, please close the issue.

**Comment by manojkumarm** [comment] 2019-02-22 18:33
Updating the plugin fixed the error for me; thanks a lot @ychin 👍

**Comment by ychin** [comment] 2019-02-26 12:01
Closing, since this can be fixed by updating plugin.

**Closed by ychin** 2019-02-26 12:01 UTC
