### ISSUE TITLE
titlebar is dark and title is illegible

### ISSUE THREAD

**Issue by andmatand** [macvim-dev/macvim#817] opened 2018-12-12 18:58 UTC
Snapshot 152 seems to have introduced a bug where the titlebar is dark (not matching the macOS default titlebar color) and the title on it is also dark, resulting in an illegible title.

I Googled this and found that someone posted about it here (there's a screenshot for reference): https://superuser.com/questions/1382016/application-macvim-menubar-went-dark-how-can-i-fix-it

I saw this on macOS 10.12.6 (Sierra) so I don't have the new "dark mode" and the dark titlebar here does not match other windows' titlebars (or the color of the tabs in MacVim itself). I downgraded to snapshot 150 for now to work around this.

**Comment by ychin** [comment] 2018-12-13 08:07
Duplicate of #799. Fix in snapshot 153.

**Closed by ychin** 2018-12-13 08:07 UTC
