### ISSUE TITLE
MacVim opens with a completely see through window, sometimes

### ISSUE THREAD

**Issue by leesavide** [macvim-dev/macvim#64] opened 2015-08-03 18:44 UTC
I've been seeing this happen frequently since I upgraded to Mac OS X 10.11 beta (I'm on the 15A234d build at the time of writing this). When opening any file in MacVim, whether from the terminal or via opening it within MacVim itself, MacVim will open with a completely see through window. As in: no text is rendered, but MacVim knows it exists and will redraw the text when movement through it is made (see below:)

Initial startup:
![macvim 1.png](https://cloud.githubusercontent.com/assets/1916661/9044492/a0c2810e-39e2-11e5-89a4-31ea4ad08e8e.png)

The text is "there" but only shown after you move through it:
![macvim 2](https://cloud.githubusercontent.com/assets/1916661/9044637/808541a0-39e3-11e5-846b-0761e5584329.png)

Then I went to see the terminal, and boy was I surprised:
![macvim terminal whoa nelly furtada](https://cloud.githubusercontent.com/assets/1916661/9044843/fa86336e-39e4-11e5-945a-5b5c9f398aa7.png)

I'm not sure if it has to do with the transparency setting on my vimrc or not, or if it has to do with a deprecated method of rendering text in the beta of Mac OS X. Either way, my vimrc & plugin configurations are [here](https://github.com/laughingman182/vimrc). I'm in the process of cleaning my vimrc and plugins, and I've built a separate MacVim, changing the headers so that by default, the custom MacVim will have a "sandboxed" runtime path, leaving the configurations in `~/.vim` alone. Instead, the custom MacVim loads it's runtime completely within it's Resources folder, i.e., in this case, it's set to load from `~/Applications/DevTools/MacVim.app/Contents/Resources/vim/.vim`, as well as from the runtime within the `Resources` folder. Unfortunately, even this custom build is showing this bug as well, meaning either transparency has to be disabled, or if it's actually a bug with MacVim itself. Any help or information as to what is happening here would be appreciated. Thank you! :)

**Comment by 9mm** [comment] 2015-10-20 03:07
I have the same issue, when I open vim from terminal a lot of times it will be 100% transparent except for text characters. I have to redraw it to get it to fill, by resizing or whatever.

Happened when i upgraded to 10.11

**Comment by limintang** [comment] 2015-11-02 18:35
Just saw the same issue. The easiest way to reproduce this issue (also 100% reproducible) is to open two tabs, stay on the right tab, then use mouse cursor to close the left tab.

Two notes:
1. Close the right tab first, or switch to the left tab first then close it, issue does not happen.
2. Unselect the option "Use Core Text Render" in the preference panel (i.e. disable transparency), this issue does not happen, either. So this should be MacVim issue, not related to any plugin.

**Comment by splhack** [comment] 2015-11-05 05:42
Could you check https://github.com/macvim-dev/macvim/pull/110 ?

**Comment by chdiza** [comment] 2015-11-05 05:57
Also, be sure that when you're launching from the Terminal you're doing `mvim -u NONE -U NONE -N`, so that we can rule out interference from `.[g]vimrc` and `.vim/`.

**Comment by limintang** [comment] 2015-11-05 08:12
The issue seems fixed by #110. Thanks.

**Comment by splhack** [comment] 2015-11-05 17:34
how about you @leesavide @9mm ?

**Comment by 9mm** [comment] 2015-11-05 17:34
seems to be fine for me so far!

**Comment by splhack** [comment] 2015-11-05 23:46
If you still have the issue, feel free to reopen it or create a new issue

**Closed** 2015-11-05 23:46 UTC
