### ISSUE TITLE
Get rid of warnings

### ISSUE THREAD

**Issue by splhack** [macvim-dev/macvim#140] opened 2015-11-15 19:22 UTC
- [x] beginModalSheetForWindow #80
- [ ] PSMTabDragAssistant.m dragImage
- [x] MMCoreTextView.m NSCopyBits #88
- [x] Use Xcode format 3.2 and recommended settings
  - Xcode 3.2 or later, it means OS X 10.6 or later can use Xcode format 3.2, thus, somebody needs to keep and maintain the old Xcode project in the repository (no need to create a branch, just copy to MacVim_legacy.xcodeproj or something from the original one. and modify Makefile a bit) if the person still wants to build MacVim on OS X 10.5 or earlier.
  - https://github.com/macvim-dev/macvim/tree/fix/xcodeproj-warnings is ok but I want to keep the content and the order of the current project file and Info.plist as much as possible.

**Comment by chdiza** [comment] 2015-11-15 20:41
We need to create either a branch or a pseudo-fork for 10.4 and 10.5 anyway.  Not because of this proposed change to Xcode 3.2, but because building on such systems is bound to break any minute now that we keep mucking about with text rendering.  We need to decide whether it will be a branch of this repo, or whether to make a fake fork of this repo under our organization.

Until we decide, I have no objection to MacVim_legacy.xcodeproj idea, but I don't know anything about makefiles, so someone else will have to make the changes.

What I'd like to know is: what's to be gained by switching to Xcode 3.2?  Is that supposed to get rid of the warnings @splhack mentioned?

**Comment by splhack** [comment] 2015-11-15 21:16
> What I'd like to know is: what's to be gained by switching to Xcode 3.2?

As I already mentioned, in order to get rid of warnings. That's all.

**Comment by chdiza** [comment] 2015-11-15 21:23
> As I already mentioned, in order to get rid of warnings

I don't see any warnings other than the `PSMTabDragAssistant.m dragImage` and `MMCoreTextView.m NSCopyBits` you mentioned.  Is Xcode 3.2 supposed to fix THOSE, or is it supposed to fix others?   It wasn't clear to me from your post; it looked like a *third* unrelated thing.

**Comment by splhack** [comment] 2015-11-15 21:43
then it doesn't affect your environment at all. never mind. I'll prepare MacVim_legacy.xcodeproj and Makefile anyway.

**Comment by osheroff** [comment] 2016-11-14 01:13
i was going to go cleanup some deprecation warnings, since whynot, they bother me.  Is the official decision that the master branch here targets 10.6+?  would be nice to know what to `ifdef` and what to change wholesale.

**Comment by splhack** [comment] 2016-11-14 03:26
@osheroff what do you mean "some deprecation warnings"? There is only one warning in the code base.

    /Users/travis/build/macvim-dev/macvim/src/MacVim/PSMTabBarControl/source/PSMTabDragAssistant.m:180:14: warning: 'dragImage:at:offset:event:pasteboard:source:slideBack:' is deprecated: first deprecated in macOS 10.7 - Use -beginDraggingSessionWithItems:event:source: instead [-Wdeprecated-declarations]
        [control dragImage:dragImage at:cellFrame.origin offset:offset event:event pasteboard:pboard source:control slideBack:YES];
                 ^

**Comment by osheroff** [comment] 2016-11-14 03:31
https://gist.github.com/osheroff/9d0a6e9d8606e8eaa13265b9154fc305

**Comment by splhack** [comment] 2016-11-14 03:35
What was that??

Travis CI build log
https://travis-ci.org/macvim-dev/macvim/builds/175424743
https://api.travis-ci.org/jobs/175424744/log.txt?deansi=true

**Comment by osheroff** [comment] 2016-11-14 03:40
yeah but that's targeting osx 10.8
https://travis-ci.org/macvim-dev/macvim/builds/175424743#L35

**Comment by splhack** [comment] 2016-11-14 04:02
@osheroff sorry I don't get your point. You mean you need 10.6+ binary? or you got https://gist.github.com/osheroff/9d0a6e9d8606e8eaa13265b9154fc305 warnings when you set MACOSX_DEPLOYMENT_TARGET to 10.7 or earlier?

**Comment by osheroff** [comment] 2016-11-14 04:06
i get the warnings when compiling on 10.12.

**Comment by osheroff** [comment] 2016-11-14 04:13
(on my mac)

**Comment by splhack** [comment] 2016-11-14 04:39
@osheroff are you using the master branch? https://github.com/macvim-dev/macvim/commits/master I've double checked it on 10.12 with Xcode 8 (Xcode 8.1 must be the same result), there is the only one warning as I wrote before.

**Comment by osheroff** [comment] 2016-11-14 04:44
oh, hell.  I had a stale fork, hadn't merged with upstream.  a million apologies for the wasted time.

**Comment by eirnym** [comment] 2019-04-01 22:27
Is this issue still actual? As far as I see, codebase has changed and it's a good idea to close this issue and open a similar if required.

**Comment by ychin** [comment] 2019-04-02 15:22
Thanks for following up. I have some ongoing work to clean up the warnings in a branch. I will maybe close it out when I commit those. Maybe I should tackle this in phases instead of being too ambitious. The current plan is to eventually move to warnings as errors and turn off the warnings that we think are frivolous. The issue is all the deprecation warnings. Let me think about this a little bit.

**Comment by eirnym** [comment] 2019-04-05 08:14
In my humble opinion, it's always easier to review and commit such changes in chunks to see how process is going and have smaller portions to review.

**Comment by ychin** [comment] 2020-12-27 03:54
Closing this issue. This discussion is horribly outdated. I will make new issues/PRs to handle existing warnings.

Some deprecation warnings are hard to get rid of but the goal is to drive to a point where we can turn on treating warnings as errors as I have personally seen bugs introduced that threw compiler warnings but ignored.

**Closed by ychin** 2020-12-27 03:54 UTC
