### ISSUE TITLE
Bug displaying unicode characters above BMP with "syntax on"

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#30] opened 2015-05-04 18:05 UTC
_From @GoogleCodeExporter on March 16, 2015 9:26_

```
What steps will reproduce the problem?
Set syntax on (latex for instance) and add a calligraphic A in math mode 
(U+1D49C) between parenthesis, itself and between dollars $(A)$. I use 
EversonMono font.


What is the expected output? What do you see instead?
I expect it to be displayed properly but sometimes, a space is displayed after 
the A, shift the rest of the line up to the $

What version of MacVim and OS X are you using (see "MacVim->About MacVim"
and  "Apple Menu->About This Mac" menu items, e.g. "Snapshot 40, 10.5.6
Intel")?
Snapshot 73

Please provide any additional information below.

Attached the screenshots of normal buggy display, normal display and syntax off 
display.
```

Original issue reported on code.google.com by `harold.c...@gmail.com` on 9 Jan 2015 at 2:09

Attachments:
* [bug1.tiff](https://storage.googleapis.com/google-code-attachments/macvim/issue-524/comment-0/bug1.tiff)
* [bug2.tiff](https://storage.googleapis.com/google-code-attachments/macvim/issue-524/comment-0/bug2.tiff)
* [bug3.tiff](https://storage.googleapis.com/google-code-attachments/macvim/issue-524/comment-0/bug3.tiff)

_Copied from original issue: douglasdrumond/macvim#524_

**Comment by jpetrie** [comment] 2015-05-09 17:32
For what it's worth, I can still reproduce this as well as of snapshot 76:
- Copy this character: 𝒜 (the Unicode character referenced in the original post; hopefully Github preserves it).
- Launch MacVim, paste the character inside a set of parentheses and type some text after (so you have a line like "(𝒜) hello." Make sure there's a line below this text.
- Exit insert mode, move the cursor to the start of the line. Move left and right between the first and second lines and note how the display of the line shifts, sometimes visually truncating the last character in the line.

**Comment by splhack** [comment] 2015-11-07 02:46
I can't reproduce it.

**Comment by splhack** [comment] 2015-11-07 17:05
@jpetrie could you write more specific way to reproduce the issue? for example

1. Open an empty MacVim window
2. Enter insert mode
3. Paste "(𝒜) hello." and enter return.
4. Input "aaaa"
5. Exit insert mode
6. ...

**Comment by jpetrie** [comment] 2015-11-07 17:17
I can still see it by doing the following:
- Make sure the Core Text renderer is enabled.
- Launch MacVim or otherwise open a new, empty buffer.
- Enter insert mode.
- Paste the text inside quotes: " (𝒜) test" (that's space, open-paren, 𝒜, close paren, space, 'test')
- Exit insert mode
- Use h and l to scrub the cursor along the line, particular to the start of the line, observe the rendering artifacts.

**Comment by splhack** [comment] 2015-11-08 03:09
what is 'the rendering artifacts'?? snapshot-81, 10.11, I can't see any issue. could you record screencast?

**Comment by splhack** [comment] 2015-11-08 03:32
@jpetrie are you using snapshot-80 or earlier version?
<img width="74" alt="snapshot-80" src="https://cloud.githubusercontent.com/assets/81904/11018606/19c10c94-8586-11e5-9b0a-101023b9b55f.png">
snapshot-81 has no problem.
<img width="79" alt="snapshot-81" src="https://cloud.githubusercontent.com/assets/81904/11018607/1b3305dc-8586-11e5-8f85-3ef4cf1f44c7.png">

**Comment by jpetrie** [comment] 2015-11-08 22:01
Yeah, it's fixed in 81+.

**Closed by jpetrie** 2015-11-08 22:01 UTC
