### ISSUE TITLE
cmd + ` not switching windows

### ISSUE THREAD

**Issue by acatighera** [macvim-dev/macvim#940] opened 2019-09-10 16:18 UTC
The OSX switch window within application shortcut doesn't work.

**Describe the bug**
The cmd + ` shortcut for OSX to switch windows doesn't do anything. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `mvim .`
2. Use cmd + N to open new window
3. Use cmd + ` to try to switch to old window
4. Nothing happens

**Expected behavior**
Expected to switch back to old window

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 On osx 10.14.5 with  8.1.1722 (157)

**Additional context**
Using full screen for both windows

**Comment by eirnym** [comment] 2019-09-11 20:03
@acatighera Thank you for an issue, 

This issue is for a long time with MacVim, and I haven't seen if anyone wrote about. It does switch, actually. But you should press keys a few times before the first switch during the application run. I don't know the exact reason. It feels like there's "ghost" windows to cycle through to eliminate with switching to them.

And it doesn't depend if windows are fullscreen or not.

**Comment by ychin** [comment] 2019-10-08 06:47
That's funny because I don't see this myself.  @eirnym / @acatighera if you can reproduce the issue can you also include what settings you have? Can you try to run MacVim with `mvim --clean` and see if it exhibits the issue? Also, please include you MacVim system defaults (see https://github.com/macvim-dev/macvim/wiki/Reporting-an-Issue for more details):

    defaults read org.vim.MacVim | grep 'MM\|SU'

I'm also curious how you launch MacVim, and how you install it (Homebrew vs official binaries, etc).

**Comment by eirnym** [comment] 2019-10-08 19:25
I have `10.15 Beta (19A582a)` (Public Beta 10)

```
    MMAutosaveColumns = 84;
    MMAutosaveRows = 47;
    MMCurrentPreferencePane = General;
    MMTopLeftPoint = "{1057, 1027}";
    "NSWindow Frame SUUpdateAlert" = "530 487 620 392 0 0 1680 1027 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2019-10-08 15:41:31 +0000";
    SUSendProfileInfo = 0;
```

It seems like the window switching was fixed. Probably by Catalina itself or by fixing another side-issue. The setting weren't changed for years and I bet that I've seen the same problem on previous betas of Catalina.

**Comment by ychin** [comment] 2019-11-03 12:24
I'm closing this issue as I'm not getting more responses and data to repro, and I personally couldn't reproduce the issue.

**Closed by ychin** 2019-11-03 12:24 UTC
