### ISSUE TITLE
MacVim 8.1.560 doesn't start - Caught deadly signal ABRT

### ISSUE THREAD

**Issue by adam-ah** [macvim-dev/macvim#807] opened 2018-12-09 06:58 UTC
OS: MacOS High Sierra 10.13.6 (17G65)
Command line crashes with the following, gui starts opening and crashes when the window would open after a quick flash. 8.1.280 works fine.

```
$ vim
Vim: Caught deadly signal ABRT
Vim: Finished.
Abort trap: 6
```

```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  5 2018 11:32:33)
macOS version
Included patches: 1-560
Compiled by travis@Traviss-Mac-6.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +timers
++builtin_terms    -gettext           +num64             +title
+byte_offset       -hangul_input      +odbeditor         +toolbar
+channel           +iconv             +packages          +transparency
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           +python/dyn        +viminfo
+conceal           +linebreak         +python3/dyn       +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua/dyn           +ruby/dyn          +writebackup
+dialog_con_gui    +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       -xpm
-ebcdic            +mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE 
```

**Comment by adam-ah** [comment] 2018-12-10 10:35
```
$ defaults read org.vim.MacVim | grep 'MM\|SU'
    MMAutosaveColumns = 203;
    MMAutosaveRows = 65;
    MMCurrentPreferencePane = Advanced;
    MMLastWindowClosedBehavior = 2;
    MMTopLeftPoint = "{211, 1177}";
    "NSWindow Frame SUUpdateAlert" = "650 588 620 392 0 0 1920 1177 ";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2018-12-09 06:49:59 +0000";
    SUSendProfileInfo = 0;
```

I'm not sure this is what you meant, but to save time in case you did:

```
$ python --version
Python 2.7.10
```

```
$ perl --version

This is perl 5, version 26, subversion 2 (v5.26.2) built for darwin-thread-multi-2level

Copyright 1987-2018, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

```
$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
```

**Comment by minghz** [comment] 2018-12-10 15:38
I got an issue where MacVim starts, but the window is completely black, and will not show any text no matter what commands you issue.

Normal vim on the terminal works for me. On MacOS Mojave.

**Comment by ychin** [comment] 2018-12-11 08:12
@minghz That's duplicate of another bug #801 . It's fixes in master and will be released soon.

To get around that without needing to update to the new version, do `defaults delete org.vim.MacVim MMUseCGLayerAlways` (it's described more in detail in the linked issue).

**Comment by ychin** [comment] 2018-12-11 08:15
@adam-ah Hmm sorry it's a little hard to figure out what's wrong. Can you try `vim --noplugin` (run Vim without any plugins) and `vim -u NONE -U NONE` (run Vim without any plugins and vimrc) to see if that fixes the issue?

**Comment by ychin** [comment] 2018-12-11 08:16
Also, if you could follow the steps listed [here](https://github.com/neovim/neovim/wiki/Development-tips#backtrace-macos--osx) that would be awesome too.

**Comment by ychin** [comment] 2019-02-11 09:58
Closing as there have been newer versions of MacVim released since this issue was filed and I don't have more information to debug. File another issue if you still see MacVim crashing.

**Closed by ychin** 2019-02-11 09:58 UTC
