### ISSUE TITLE
Upgraded to Mac OS 10.15, the string is truncated

### ISSUE THREAD

**Issue by ccworld1000** [macvim-dev/macvim#951] opened 2019-10-09 06:05 UTC
_Instructions: Upgraded to Mac OS 10.15, the string is truncated

**Describe the bug**
Upgraded to Mac OS 10.15, the string is truncated
Enter the lowercase q

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `MacVim`
2. Input `test11qqq`

**Expected behavior**
Truncated String Displays Normal

**Screenshots**
![EBFEC261-8C05-42B6-AF1A-3989D95E4840](https://user-images.githubusercontent.com/22360168/66455512-9e69a700-ea9d-11e9-94c2-ceaddfe7b2fd.png)

**Environment (please complete the following information):**
 - Vim version 8.1.280
 - OS: macOS 10.15
 - Terminal: GUI MacVim

**Additional context**
'q' the string is truncated

**Comment by eirnym** [comment] 2019-10-09 08:07
@ccworld1000 Thank you for an issue,

Please, look into #905 as yours seems to be a full duplicate of it.

**Comment by ychin** [comment] 2019-10-10 10:43
I think this is a dup of #905. Update will be released this weekend.

**Closed by ychin** 2019-10-10 10:43 UTC
