### ISSUE TITLE
Screen flashes black & other random behavior in Mojave

### ISSUE THREAD

**Issue by aholub** [macvim-dev/macvim#794] opened 2018-12-02 02:24 UTC
I don't know how to say it other than the screen goes completely nuts in Mojave. It flashes black when I try to move the cursor, goes entirely black when I type ":",  formats in odd ways. seems to jump around in the file. It's just generally bonkers. I fixed it by issuing the following:

```defaults write org.vim.MacVim MMUseCGLayerAlways -bool YES```

which I don't  understand, but got from an earlier post for a similar problem. The attached .zip holds a .mov video screen capture of the problem. All I'm doing is issuing a sequence of j commands, finishing up with a :q .

[VIM-bug.mov.zip](https://github.com/macvim-dev/macvim/files/2636533/VIM-bug.mov.zip)

**Comment by aholub** [comment] 2018-12-02 08:37
Actually, the `defaults` fix doesn't fully fix the problem. I'm still seeing occasional bad behavior. The last time macvim crashed entirely. I've attached the crash report.

[report.txt](https://github.com/macvim-dev/macvim/files/2636762/report.txt)

**Comment by arturoherrero** [comment] 2018-12-02 14:18
I have the same problem. I'm not sure if this issue is the same issue described in #751.

**Comment by longcao** [comment] 2018-12-02 15:06
I'm also seeing this on macOS Mojave 10.14.1, installed with Homebrew:

```
macvim: stable 8.1-151 (bottled), HEAD
GUI for vim, made for macOS
https://github.com/macvim-dev/macvim
Conflicts with:
  vim (because vim and macvim both install vi* binaries)
/usr/local/Cellar/macvim/8.1-151_2 (2,178 files, 34.9MB) *
  Poured from bottle on 2018-12-01 at 09:16:45
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb
==> Dependencies
Required: cscope ✔, lua ✔, python ✔
==> Requirements
Build: xcode ✔
==> Options
--HEAD
	Install HEAD version
```

@aholub And for what it's worth, disabling the Core Text renderer and and restarting MacVim as noted in https://github.com/macvim-dev/macvim/issues/751#issuecomment-427593064 seems to fix the issue for me for now.

**Comment by tkandal** [comment] 2018-12-03 16:59
Hello

After upgrading to latest MacVim on MacOS 10.14.1 with Homebrew, I also have this problem.
Disabling the Core Text renderer as noted in https://github.com/macvim-dev/macvim/issues/751#issuecomment-427593064 also fixed my issue.

**Comment by arturoherrero** [comment] 2018-12-03 19:42
I also disabled the Use Core Text renderer from the preferences and MacVim seems to be stable but I've lost the typography I use and it looks worse.

**Comment by ychin** [comment] 2018-12-04 08:19
This is a duplicate of #751, and PR #757 just fixed this. Closing.

@arturoherrero  Just curious though what did you mean by "losing the typography"? You should be able to turn on Core Text renderer again (which is the default supported path) but I'm curious what the issue was in the non-Core Text renderer.

**Closed by ychin** 2018-12-04 08:19 UTC

**Comment by arturoherrero** [comment] 2018-12-04 11:13
@ychin I'm not sure if you can appreciate with the screenshots.

This is the default preferences:
![macvim default preferenes](https://user-images.githubusercontent.com/392222/49438076-26fc2480-f7b5-11e8-9625-6bd3e0b000ee.jpg)

This is the disabled the Use Core Text renderer, the editor looks worst. The NERDTree separation is not straight and there is slightly more space between the elements.
![macvim disabled core render](https://user-images.githubusercontent.com/392222/49438082-2a8fab80-f7b5-11e8-850c-e382c9bb0a26.jpg)

**Comment by ychin** [comment] 2018-12-04 11:16
Ah ok. Yeah that looks about what I would expect. Hope the fix solved the issue for you.

**Comment by arturoherrero** [comment] 2018-12-04 11:16
Thanks a lot!
