### ISSUE TITLE
Graphical Glitches

### ISSUE THREAD

**Issue by AdamJacobMuller** [macvim-dev/macvim#792] opened 2018-11-29 02:57 UTC
Hi,

Installing (from HomeBrew) the latest version of MacVim results in major graphical glitches for me.

https://www.youtube.com/watch?v=7XKMYM5KM0k

That is version `8.1-151_2`

Testing with `8.1-149_1` (what was on my old laptop) seems to work fine.

I can probably get some `git bisect` magic working if required to narrow the issue down further.

**Comment by wlaurance** [comment] 2018-11-29 03:05
Hi, there I am also getting this same behavior. Thanks for reporting @AdamJacobMuller

**Comment by numbcoder** [comment] 2018-11-29 03:20
I have got the same behavior on `8.1-151_1` and `8.1-151_2`

After disabled the `Use Core Text render` option, this behavior disappeared.

**Comment by ychin** [comment] 2018-11-29 10:49
Closing as duplicate of #751. There should be a fix by end of week.

**Comment by ychin** [comment] 2018-11-29 10:49
For ways of mitigating this for now, refer to the other issue, but you could download a binary from our releases or turn off Core Text Renderer for now.

**Closed by ychin** 2018-11-29 10:49 UTC
