### ISSUE TITLE
E432: Tags file not sorted...

### ISSUE THREAD

**Issue by JezuzStardust** [macvim-dev/macvim#953] opened 2019-10-10 11:35 UTC
**Describe the bug**
Installing Macvim from HEAD and using trying to open the manual causes the following error: 

`E432: Tags file not sorted: /usr/local/Cellar/macvim/HEAD-dc07a14/MacVim.app/Contents/Resources/vim/runtime/doc/tags` 

I also get the same error for all my plugins at the same time. Also, when navigating the help pages the error appears for each new help file that is opened. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `brew uninstall macvim && brew install macvim --HEAD`
2. Type `:h<enter>` and the error appears on the bottom of the window. 
3. Press `<enter>` to continue and click on any link (or use `<CTRL-]>` and the error appears again (but with reference to other help files). 
4. Describe the error

**Expected behavior**
No error message. 

**Environment (please complete the following information):**
 - Vim version 8.1.2102 
 - OS: macOS 10.15 (Catalina)
 - Terminal: GUI

**Comment by eirnym** [comment] 2019-10-10 11:52
@JezuzStardust Thank you for an issue. It's intended behavior. I have quite a few of the same as well since `MacVim build 157 (vim patch level  8.1.1722)` was out as I use official GitHub build.

The error [is shown](https://github.com/vim/vim/blob/e2c453d38f6512ac4cff7cd26aa7780b4e2534d7/src/tag.c#L2723) because `vim` was compiled with `tag_binary` feature and `tagbsearch` option enabled by default by vim runtime. The option default was changed in the [upstream](https://github.com/vim/vim).

I suggest to update all the plugins and check if any of these errors remain and, if any, create issues to respective plugin repositories to actually fix the issue.

On the other hand you ... can turn off the `tagbsearch` option and somebody else will do the same as above. 

I personally prefer the first option.

**Comment by JezuzStardust** [comment] 2019-10-10 11:57
I agree and I will create issues for the relevant plugins. 

However, the strange thing is that this error seems to also occur for vim's own manual files. Shouldn't that have been fixed upstreams in vim itself then?

**Comment by eirnym** [comment] 2019-10-10 12:09
It's better if you'd compile vim from upstream and check if their file has an error. (don't forget to compile with `tag_binary` and make sure that you've enabled `tagbsearch` option). If there's no error, then the problem is somewhere in this repo and should be fixed.

**Comment by JezuzStardust** [comment] 2019-10-11 06:49
The problem is upstreams: 

https://github.com/vim/vim/issues/5039

**Closed** 2019-10-11 06:48 UTC

**Comment by JezuzStardust** [comment] 2019-10-16 11:15
@eirnyum, I am a bit new here and I am not sure how things work. However, it seems like there is now a fix in the latest commit on Master on Vim/Vim. Should I reopen this to make sure that that commit is pulled into macvim or will that happen automatically later when this is updated? I.e. is macvim built on the latest master of vim or does it have its own branch?

**Comment by eirnym** [comment] 2019-10-16 18:15
Periodically changes from upstream are manually merged to `MacVim`, and it may happen that exactly these changes won't be included into the nearest release (which was already out).

**Comment by ychin** [comment] 2019-10-17 06:42
I'm still in the middle of releasing snapshot-158. Since this bug seems like a relatively annoying issue for Catalina, I will just make a new release for it with the latest changes and skipping snapshot-158 and go to snapshot-159. (Not going to rebase and re-tag the commits since last time I did that it screwed up Homebrew)

**Comment by eirnym** [comment] 2019-10-17 07:49
@ychin you can disable the default `tagbsearch` as a workaround and release `158`.
