### ISSUE TITLE
Python support broken in 109 on OS X 10.9.5

### ISSUE THREAD

**Issue by RubenVerborgh** [macvim-dev/macvim#350] opened 2016-09-13 11:57 UTC
When upgrading to version 8.0 (109), Python support broke on OS X 10.9.5. When starting Vim, I get:

```
Error detected while processing function <SNR>24_InitializePythonBuiltin:
line   23:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
Error detected while processing function <SNR>24_InitializePythonBuiltin:
line   23:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
```

The package requiring Python is [editorconfig-vim](https://github.com/editorconfig/editorconfig-vim).

**Comment by krid78** [comment] 2016-09-13 12:11
I see a similar issue with UltiSnips.

This is a possible duplicate of #349

**Comment by Viqsi** [comment] 2016-09-13 12:22
I'm getting the same issue with [simplenote.vim](https://github.com/mrtazz/simplenote.vim) on OSX 10.11.6, so it's not confined to Mavericks.

**Comment by oluckyman** [comment] 2016-09-13 13:12
Just updated to 8.0.3. and getting "Sorry, this command is disabled" while starting (because of YouCompleteMe plugin).
Also the same error when run command `:py import sys`

**Comment by liming01** [comment] 2016-09-13 23:44
I get same error for YouCompleteMe plugin in macvim 8, however all versions of macvim 7 works fine.

YouCompleteMe unavailable: dlopen(/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not foun
d: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

**Comment by splhack** [comment] 2016-09-14 03:47
Fixed in snapshot-110 https://github.com/macvim-dev/macvim/releases/tag/snapshot-110

**Closed by splhack** 2016-09-14 03:47 UTC

**Comment by RubenVerborgh** [comment] 2016-09-14 05:57
Thanks, the fix works!
