### ISSUE TITLE
Update breaks MacVim for High Sierra

### ISSUE THREAD

**Issue by d-tork** [macvim-dev/macvim#1138] opened 2020-12-12 13:14 UTC
**Describe the bug**
MacVim no longer can open new windows or existing files.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Updated to latest version
2. Cmd+N : nothing happens
3. Cmd+O, choose a file, nothing happens

**Expected behavior**
MacVim window opens.

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: macOS 10.13.6
 - Terminal: GUI? I don't know, I'm just using the MacVim window.

**Additional context**
I went back to snapshot 166 to get a working copy. Snapshot 168 definitely not compatible with my High Sierra environment.

**Comment by mikaraunio** [comment] 2020-12-12 17:54
Snapshot 168 doesn't work for me either on 10.13.6. Launching from the command-line gives the following:

```
$ /Applications/MacVim.app/Contents/MacOS/Vim
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/MacVim.app/Contents/MacOS/Vim
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/MacVim.app/Contents/MacOS/Vim
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

**Comment by ychin** [comment] 2020-12-12 21:14
That's unfortunate. Looking into it. It's unfortunate because we turned off older macOS version's CI due to Travis CI changing their support for OSS projects, but I will see if there is a way for me to repro this.

**Comment by Carreau** [comment] 2020-12-13 03:55
Same for Sierra – Not sure if that helps or not, I'll revert to an older version for now.

**Comment by ketch** [comment] 2020-12-13 05:19
Rolling back to snapshot 166 made Macvim work again for me.

**Comment by ketch** [comment] 2020-12-13 05:20
It might be best to warn people before updating that new versions of Macvim don't support High Sierra or older versions of Mac OS.

**Comment by 0xfadeef** [comment] 2020-12-13 13:47
Same problem on El Capitan (10.11). Not reproducible with `Snapshot 166`.

**Comment by samantafluture** [comment] 2020-12-13 17:07
Same problem on Sierra (10.12).

`dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/MacVim.app/Contents/MacOS/Vim
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/MacVim.app/Contents/MacOS/Vim
  Expected in: /usr/lib/libSystem.B.dylib`

**Comment by ychin** [comment] 2020-12-13 21:38
Ok I think I found the issue. Could be a little annoying to fix but it has to do with how `gettext` (library for localization) is built against newer versions of macOS.

I will push out a fix later, but for now I fixed the auto-updater to know not to deploy this version for macOS 10.13. If you have r166 running on macOS 10.13 and check for updates it will just say it's the latest version now, so next time the updater says there is a new build it should contain the fix.

**Comment by ychin** [comment] 2020-12-20 00:48
This should be fixed under r169: https://github.com/macvim-dev/macvim/releases/tag/snapshot-169

Please try it and let me know if it doesn't work. If you reverted to 166 before, the auto-updater should be able to upgrade to 169 directly.

**Closed by ychin** 2020-12-20 00:48 UTC
Labels: Crash

**Comment by Carreau** [comment] 2020-12-20 04:17
Auto updated for me to 169, on `Sierra 10.12.6 (16G2136)`, and appear to work.

Many thanks !

**Comment by shenzhuxi** [comment] 2021-01-11 21:35
MacVim 169 on my MacBook Air (11-inch, Mid 2011) High Sierra only displayed text for a while then all the text disappeared. 

![Screen Shot 2021-01-11 at 21 34 26](https://user-images.githubusercontent.com/585720/104241005-e58ad880-5454-11eb-979c-2a3f27a687e0.png)

**Comment by ychin** [comment] 2021-02-09 06:40
@shenzhuxi is that still happening to you? Do you have Core Text renderer enabled? (It should be) If it's still not working can you file a new issue? This is not the same problem as what this issue was tracking.
