### ISSUE TITLE
While use set guifont=Monaco:h13  than use bettertouchtool to move the window, window will flash!

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#15] opened 2015-05-04 18:01 UTC
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
RULES: READ FIRST!
1.  This page is only for reporting bugs.  Feature requests are to be
posted to the [http://groups.google.com/group/vim_mac vim_mac] mailing
list.
2.  Go through the
[http://github.com/b4winckler/macvim/wiki/Troubleshooting Troubleshooting
guide] before creating a new Issue to rule
out common problems that are not bugs.
3.  Search older Issues and the [http://groups.google.com/group/vim_mac
vim_mac] mailing list before creating a new Issue.
(Please delete this text now that you have read it and enter an issue
report.  Thank you for taking the time to report bugs!)

What steps will reproduce the problem?


What is the expected output? What do you see instead?


What version of MacVim and OS X are you using (see "MacVim->About MacVim"
and  "Apple Menu->About This Mac" menu items, e.g. "Snapshot 40, 10.5.6
Intel")?


Please provide any additional information below.

```

Original issue reported on code.google.com by `13wei.qi...@gmail.com` on 20 Oct 2014 at 3:54

_Copied from original issue: douglasdrumond/macvim#516_

**Comment by jpetrie** [comment] 2015-10-10 23:57
I'm going to close this as it *sounds* like it might be a duplicate of https://github.com/macvim-dev/macvim/issues/32 and if it isn't there's basically no reproduction steps or detail in the bug itself.

**Closed by jpetrie** 2015-10-10 23:57 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
