### ISSUE TITLE
MacVim compilation hangs on PSMTabBarControl

### ISSUE THREAD

**Issue by tucnak** [macvim-dev/macvim#1258] opened 2022-08-01 10:42 UTC
### Steps to reproduce

```
git clone https://github.com/macvim-dev/macvim.git
cd macvim/src
./configure --enable-rubyinterp \
            --enable-python3interp \
            --enable-perlinterp \
            --enable-cscope \
            --enable-terminal
make -j8 # or simply 'make' for that matter
```

### Expected behaviour

Well, I would expect the build to happen O.K.

### Version of Vim and architecture

9.0.124, GUI, arm64

### Environment

(iTerm 2)

I've tried with both fish and zsh— the result is the same. Note: I could in fact build the earlier version of master with the exact same parameters weeks prior, so I must say this comes off as very unusual.

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    MACOSX_DEPLOYMENT_TARGET = 12.5
    VIM_SHORT_VERSION_STRING = 9.0.124

### How MacVim was installed

git

### Logs and stack traces

```shell
User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    MACOSX_DEPLOYMENT_TARGET = 12.5
    VIM_SHORT_VERSION_STRING = 9.0.124

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: 056b6a2f03f4ebd864f4c5cb46362877
Build description path: /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/XCBuildData/056b6a2f03f4ebd864f4c5cb46362877-desc.xcbuild

note: Build preparation complete
warning: Building targets in manual order is deprecated - check "Parallelize build for command-line builds" in the project editor, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current build to suppress this warning
warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 12.5, but the range of supported deployment target versions is 10.9 to 12.3.99.
CreateBuildDirectory /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build
    cd /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/MacVim.xcodeproj
    builtin-create-build-directory /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build

CreateBuildDirectory /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/qlstephen/build
    cd /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/MacVim.xcodeproj
    builtin-create-build-directory /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/qlstephen/build

CreateBuildDirectory /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/qlstephen/build/Release
    cd /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/MacVim.xcodeproj
    builtin-create-build-directory /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/qlstephen/build/Release

CreateBuildDirectory /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/Release
    cd /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/MacVim.xcodeproj
    builtin-create-build-directory /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/Release

/Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/PSMTabBarControl/PSMTabBarControl.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 12.5, but the range of supported deployment target versions is 10.9 to 12.3.99. (in target 'PSMTabBarControlFramework' from project 'PSMTabBarControl')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'PSMTabBarControlFramework' from project 'PSMTabBarControl')
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'PSMTabBarControlFramework' from project 'PSMTabBarControl')
MkDir /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/Release/PSMTabBarControl.framework (in target 'PSMTabBarControlFramework' from project 'PSMTabBarControl')
    cd /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/PSMTabBarControl
    /bin/mkdir -p /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/Release/PSMTabBarControl.framework

... many more lines of build detail ...

2022-08-01 13:33:06.190 ibtoold[98202:1557123] NSFileCoordinator is doing nothing.
/* com.apple.actool.compilation-results */
/Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/assetcatalog_generated_info.plist
/Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/Release/PSMTabBarControl.framework/Versions/A/Resources/Assets.car


ProcessInfoPlistFile /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/Release/PSMTabBarControl.framework/Versions/A/Resources/Info.plist /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/PSMTabBarControl/PSMTabBarControlFramework-Info.plist (in target 'PSMTabBarControlFramework' from project 'PSMTabBarControl')
    cd /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/PSMTabBarControl
    builtin-infoPlistUtility /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/PSMTabBarControl/PSMTabBarControlFramework-Info.plist -producttype com.apple.product-type.framework -expandbuildsettings -platform macosx -additionalcontentfile /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/assetcatalog_generated_info.plist -o /Users/illia.kovalevskyy/Waresoft/macvim/src/MacVim/build/Release/PSMTabBarControl.framework/Versions/A/Resources/Info.plist

... and this is where it hangs ...
```

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment] 2022-08-05 21:48
Hmm, I can't quite reproduce this. One thing that stands out to me is that your `MACOSX_DEPLOYMENT_TARGET` is 12.5, but on mine is 12.4. I manually set it to 12.5 and it still seems to be able to build just fine.

What Xcode version are you using? Are you using the Xcode 14 beta?

**Comment by ychin** [comment] 2022-08-11 22:21
Hi @tucnak  any update on this? I'm still not seeing this, so I wonder if there is any odd configuration issues here. I will probably close this issue if I don't hear back (can always reopen later).

**Closed** 2022-08-26 12:29 UTC
Labels: Response Needed

**Comment by tucnak** [comment] 2022-08-26 12:31
I'm sorry, I had to triage this with a spare machine and the issue came down to a very esoteric issue having to do with LD_LIBRARY_PATH, namely adding certain libraries influenced the clang build process in unprecedented ways; I couldn't figure out what went wrong exactly, but when I cleared my environment and rebuilt everything from scratch— everything went back to normal.
