### ISSUE TITLE
Terminal color test gives unexpected results

### ISSUE THREAD

**Issue by lifepillar** [macvim-dev/macvim#599] opened 2017-11-20 11:52 UTC
There appears to be something wrong with the handling of some colors in the terminal, as this screenshot shows:

<img width="1039" alt="mavim-true-colors" src="https://user-images.githubusercontent.com/1193314/33017015-002e25b8-cdf1-11e7-96e2-a07a8e16702e.png">

For the test I am using [this script](https://gist.github.com/lifepillar/09a44b8cf0f9397465614e622979107f). 

For comparison, this is how the output looks in Vim's terminal when Vim is run in iTerm2:

<img width="950" alt="iterm2-vim-colors" src="https://user-images.githubusercontent.com/1193314/33017154-844b3ef8-cdf1-11e7-87f5-6a8f08b302c9.png">

So, this seems to be a MacVim-specific problem.

**Comment by semanser** [comment] 2017-12-01 19:07
Possible related to #579

**Comment by eirnym** [comment] 2018-05-30 10:51
Something is wrong with your script as This is how it looks in `Terminal.app`. Other rainbow color scripts produce expected results

![zrzut ekranu 2018-05-30 o 12 49 37](https://user-images.githubusercontent.com/485399/40716087-184a9fc0-6408-11e8-8d55-c84d977ee983.png)

**Comment by lifepillar** [comment] 2018-06-02 15:28
I cannot reproduce this any longer with MacVim 8.1.22. Thanks!

**Comment by eirnym** [comment] 2019-05-18 10:43
@lifepillar Please, close the issue if you can't reproduce it.

**Closed** 2019-05-21 17:06 UTC
